<?php
$this->headTitle()->prepend($magazine->getName());
?>
<ol class="breadcrumb">
  <li><a href="<?= $this->url('home') ?>">Home</a></li>
  <li class="active"><?= $magazine->getName() ?></li>
</ol>
<?= $this->partial(
  'magazines/index/_image',
  array(
    'image' => $image,
  )
) ?>
<h2><?= $magazine->getName() ?></h2>
<? foreach($articles as $article): ?>
    <h3><a href="<?= $this->url(
        'article',
        array('id' => $article->getId())
    ) ?>"><?= $article->getTitle() ?></a></h3>
<? endforeach; ?>
